version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
    commit-message:
      prefix: "build(deps)"
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci(deps)"
      include: scope
